### ISSUE TITLE
Missing code for column and node tests in Scalefree Nodes

### ISSUE THREAD

**Issue by EThromIFM** [ScalefreeCOM/datavault4coalesce#10]
With the Scalefree Nodes Column and Node Tests can not be executed, because the following code lines are missing in the Node Definition and in the Run Template:

Node Definition:
```
displayName: Enable Tests
attributeName: testsEnabled
type: toggleButton
default: true
```

Run Template:
```
{% if config.testsEnabled %}
    {% for test in node.tests %}
        {% if test.runOrder == 'After' %}
            {{ test_stage(test.name, test.continueOnFailure) }}
            {{ test.templateString }}
        {% endif %}
    {% endfor %}

    {% for column in columns %}
        {% for test in column.tests %}
            {{ test_stage(column.name + ": " + test.name) }}
            {{ test.templateString }}
        {% endfor %}
    {% endfor %}
{% endif %}
```

**Comment by tkirschke** [comment]
Hi @jabibo and thanks for reaching out!

You are correct, we forgot about adding these code snippets!
I added them in the attached branch. Since Coalesce does not support testing on Views yet, I only added the code for all objects, where we have run templates. 

Let me know if the code in the attached branch works for you! I would then happily merge it into main.

Best regards
Tim
