### ISSUE TITLE
Not able to put PIT in different schema than HUB

### ISSUE THREAD

**Issue by jabibo** [ScalefreeCOM/datavault4coalesce#8]
It seems that it is not possible to put the PIT in a different schema than the hub.  
Problem seems to be this line of code
![image](https://github.com/ScalefreeCOM/datavault4coalesce/assets/57133231/c9c3c9ae-d14b-43a0-ae2c-3c3c9e29c116)
Version is 1.0.1

**Comment by tkirschke** [comment]
Hi @jabibo and thanks for reaching out!

I was able to reproduce the issue you mentioned. I applied the necessary changes, including the line you mentioned above.

The changes are done in the linked branch. Please review and try them out and let me know whether your issue is resolved!

Thanks for helping improve our package!
Best regards,
Tim
